spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/script_review_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: script-review-ms

server:
  port: 8080

jwt:
  secret: "nRZ1B1hOIj/gcKsvS0gqoyy8IyB7EBP8W9VUbpms1CbPLvYlnoKhCcXVTfb0weldnIpV2FveGnnSGERjVrFpMg=="  # >= 64 caracteres
  expiration: 86400000  # 1 dia
